### ISSUE TITLE
When I did the first application it gave me an error 

### ISSUE THREAD

**Issue by ahmet-f-gumustas** [stereolabs/zed-sdk#632]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I got an error when I ran a code in the tutorial directory and I solved it by changing the code and I want to share it.

### Steps to Reproduce

1.
2.
3.
...

### Expected Result

I dont know expected result but original code gave me an error . 

```
Traceback (most recent call last):
  File "/home/moveon2/Desktop/Desktop1/All-Projects/Python-project/StereoCamera-Explorer/tutorials/tutorial 1 - hello ZED/python/hello_zed.py", line 25, in <module>
    main()
  File "/home/moveon2/Desktop/Desktop1/All-Projects/Python-project/StereoCamera-Explorer/tutorials/tutorial 1 - hello ZED/python/hello_zed.py", line 10, in main
    init_params.sdk_verbose = False
TypeError: Argument 'value' has incorrect type (expected int, got bool)

```

And I changed Code . It's working Know . This is my code ; 
```
import pyzed.sl as sl

def main():
    # Create a ZED camera object
    zed = sl.Camera()

    # Set configuration parameters
    init_params = sl.InitParameters()
    init_params.sdk_verbose = 0  # Change False to 0

    # Open the camera
    err = zed.open(init_params)
    if err != sl.ERROR_CODE.SUCCESS:
        print(repr(err))
        zed.close()
        return

    # Capture 50 images and stop
    i = 0
    image = sl.Mat()
    while i < 50:
        if zed.grab() == sl.ERROR_CODE.SUCCESS:
            # Retrieve the left image
            zed.retrieve_image(image, sl.VIEW.LEFT)
            # Display the image
            print("Image {} captured".format(i))
            i += 1

    # Close the camera
    zed.close()

if __name__ == "__main__":
    main()
```

And This is a output ; 

```
Image 0 captured
Image 1 captured
Image 2 captured
Image 3 captured
Image 4 captured
Image 5 captured
Image 6 captured
Image 7 captured
Image 8 captured
Image 9 captured
Image 10 captured
Image 11 captured
Image 12 captured
Image 13 captured
Image 14 captured
Image 15 captured
Image 16 captured
Image 17 captured
Image 18 captured
Image 19 captured
Image 20 captured
Image 21 captured
Image 22 captured
Image 23 captured
Image 24 captured
Image 25 captured
Image 26 captured
Image 27 captured
Image 28 captured
Image 29 captured
Image 30 captured
Image 31 captured
Image 32 captured
Image 33 captured
Image 34 captured
Image 35 captured
Image 36 captured
Image 37 captured
Image 38 captured
Image 39 captured
Image 40 captured
Image 41 captured
Image 42 captured
Image 43 captured
Image 44 captured
Image 45 captured
Image 46 captured
Image 47 captured
Image 48 captured
Image 49 captured

```

### Actual Result

What I understand in your code is that it gives me information such as a serial number, but I could not get this information, I could not understand it. 

### ZED Camera model

ZED2i

### Environment

```shell
OS: Ubuntu 22.04
Camera Model : Zed 2i
```

### Anything else?

Thank You :)

**Comment by ahmet-f-gumustas** [comment]
When we make the True place zero here, it fixes

```
import pyzed.sl as sl

def main():
    # Create a Camera object
    zed = sl.Camera()

    # Create a InitParameters object and set configuration parameters
    init_params = sl.InitParameters()
    init_params.sdk_verbose = 0  # Change False to 0

    # Open the camera
    err = zed.open(init_params)
    if err != sl.ERROR_CODE.SUCCESS:
        exit(1)

    # Get camera information (ZED serial number)
    zed_serial = zed.get_camera_information().serial_number
    print("Hello! This is my serial number: {0}".format(zed_serial))

    # Close the camera
    zed.close()

if __name__ == "__main__":
    main()
```
